### ISSUE TITLE
📖 Algún libro favorito?

### ISSUE THREAD

**Issue by JoshuaMorales99** [pdepjm/2023-tp0-presentacion-MeliBugallo#1]
Buenas Mel! 👋🏻
¿Qué es lo que más te gusta leer? ¿Tienes algún libro o texto favorito?

Pd: Es muy bonito el michi 😸

**Comment by MeliBugallo** [comment]
Holaaa, honestamente puedo hablar rato largo de cuánto me gusta leer, más que nada historias, peeero siendo breve diría que lo que más me gusta es lo mucho que puedo llegar a "vivir" y sentir a través de un libro. Va desde estar en el lugar del personaje hasta la inmersión en un contexto social que no es el propio; casi casi como tener una prueba de cómo sería estar en situaciones y escenarios poco probables de experimentar.
Y bueno la respuesta del libro favorito depende de cuándo se pregunte. Actualmente el podio lo disputan "Leer Lolita en Teherán" y "La vida invisible de Addie LaRue"

¿A vos te gusta leer?
