### ISSUE TITLE
Consulta

### ISSUE THREAD

**Issue by tomasfiestas** [pdepjm/2023-tp0-presentacion-MeliBugallo#2]
Me interesa el ritual de conocimiento, no sabrás alguno de promocionar materias directamente?

**Comment by MeliBugallo** [comment]
De los rituales que probé el año pasado pareciera que el que mejor resultados dio es el de vender horas de sueño y nutrir tu alma con café. Después está la parte más administrativa de sacar los sagradas apuntes, disponerlos en círculo y absorber el conocimiento.

**Comment by tomasfiestas** [comment]
Probamos con un amigo el ritual de los apuntes en circulo para absorber el conocimiento y empezó a flotar, es normal eso? todavía sigue el techo

**Comment by MeliBugallo** [comment]
Nooo ese es un efecto no deseado, se te está escapando el conocimiento
