### ISSUE TITLE
Latín 

### ISSUE THREAD

**Issue by ArielGuerra** [pdepjm/2023-tp0-presentacion-MeliBugallo#3]
Es muy interesante lo del latín, ¿es mas difícil que el español o comparten similitudes?

**Comment by MeliBugallo** [comment]
No sabría decirte si más difícil, tienen cosas que gramaticalmente funcionan muuuuy distinto. Por ejemplo, algo en lo que difieren es que los sustantivos se declinan, eso significa que la palabra cambia su terminación según qué función cumpla en la oración. Esto de las declinaciones es algo que también tienen idiomas como el ruso o el alemán, si no me equivoco. Pero después ambos comparten las conjugaciones verbales que es algo que no se caracteriza por ser lo más fácil de aprender.
Lo bueno de estudiar latín desde el español es que hay mucho vocabulario intuitivo
